window.SOIL_QUESTION_BANK = [
  {
    id: "cec-definition",
    type: "objective",
    topic: "Soil chemistry",
    prompt: "What does a soil's cation exchange capacity (CEC) describe?",
    choices: [
      "Its capacity to hold positively charged ions on soil colloids",
      "The amount of water that drains below the root zone",
      "The rate at which soil particles are broken down by wind",
      "The proportion of air-filled pore space in dry soil",
    ],
    correctIndex: 0,
    explanation: "CEC is the capacity of soil to hold exchangeable cations on negatively charged clay and organic-matter surfaces.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "cec-increases",
    type: "objective",
    topic: "Soil chemistry",
    prompt: "Which change would generally increase a soil's cation exchange capacity?",
    choices: [
      "Increasing its clay and organic-matter content",
      "Removing its fine particles",
      "Reducing its organic matter",
      "Increasing the speed of surface runoff",
    ],
    correctIndex: 0,
    explanation: "The lecture notes that CEC generally rises as clay content and organic matter increase.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "ph-neutral",
    type: "objective",
    topic: "Soil chemistry",
    prompt: "A soil pH of 7.0 is described as:",
    choices: ["Neutral", "Strongly acidic", "Alkaline", "Saline"],
    correctIndex: 0,
    explanation: "On the pH scale described in the course material, 7.0 is neutral.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "kaolinite-layer",
    type: "objective",
    topic: "Clay minerals",
    prompt: "Which clay mineral is given as the main example of a 1:1 layer silicate?",
    choices: ["Kaolinite", "Smectite", "Vermiculite", "Illite"],
    correctIndex: 0,
    explanation: "Kaolinite is a 1:1 mineral, with one tetrahedral sheet bonded to one octahedral sheet.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "expanding-clays",
    type: "objective",
    topic: "Clay minerals",
    prompt: "Which pair is identified as expanding 2:1 clay minerals?",
    choices: ["Smectite and vermiculite", "Kaolinite and halloysite", "Quartz and feldspar", "Illite and kaolinite"],
    correctIndex: 0,
    explanation: "Water can enter the interlayer spaces of smectite and vermiculite, causing them to expand.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "soil-organism-definition",
    type: "objective",
    topic: "Soil biology",
    prompt: "Which best describes a soil organism?",
    choices: [
      "An organism that inhabits soil during all or part of its life",
      "An organism that lives only on the soil surface",
      "A mineral particle smaller than clay",
      "An organism found only in waterlogged soil",
    ],
    correctIndex: 0,
    explanation: "The biological-properties lecture defines soil organisms by their inhabiting soil for all or part of their life.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "earthworm-respiration",
    type: "objective",
    topic: "Soil biology",
    prompt: "How does an earthworm exchange gases?",
    choices: [
      "By diffusion across its moist body surface",
      "Through a pair of lungs",
      "Through gills inside its crop",
      "Through pores that pump air into its blood",
    ],
    correctIndex: 0,
    explanation: "Earthworms have no lungs; gas exchange occurs by diffusion across the body surface, which must remain moist.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "earthworm-benefit",
    type: "objective",
    topic: "Soil biology",
    prompt: "Which is one way earthworms can improve soil conditions?",
    choices: [
      "Their burrows can improve aeration and drainage",
      "They remove all organic matter from the soil",
      "They prevent soil aggregates from forming",
      "They stop water from infiltrating",
    ],
    correctIndex: 0,
    explanation: "Earthworm burrows aid aeration and drainage; their casts can also be rich in organic matter and available nutrients.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "soil-microbe-function",
    type: "objective",
    topic: "Soil biology",
    prompt: "Which is a major function of soil microorganisms?",
    choices: [
      "Breaking down organic residues and recycling nutrients",
      "Stopping all mineral weathering",
      "Preventing humus formation",
      "Removing every pore from the soil",
    ],
    correctIndex: 0,
    explanation: "The course materials identify organic-residue decomposition and nutrient cycling as key microbial functions.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "mycorrhizae",
    type: "objective",
    topic: "Soil biology",
    prompt: "What is a key benefit of a mycorrhizal fungus–root association?",
    choices: [
      "It can improve plant access to nutrients such as phosphorus",
      "It prevents roots from absorbing nutrients",
      "It converts all soil particles into clay",
      "It removes organic matter from the root zone",
    ],
    correctIndex: 0,
    explanation: "The lecture describes mycorrhizae as helping plants access nutrients, especially in infertile soils.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "water-erosion-sequence",
    type: "objective",
    topic: "Soil erosion",
    prompt: "Which sequence correctly describes the main processes of water erosion?",
    choices: [
      "Detachment, transport, deposition",
      "Deposition, detachment, weathering",
      "Transport, aggregation, detachment",
      "Leaching, compaction, deposition",
    ],
    correctIndex: 0,
    explanation: "Water erosion detaches particles, transports them, and deposits them when flow slows.",
    source: "Soil Management lecture",
  },
  {
    id: "splash-erosion",
    type: "objective",
    topic: "Soil erosion",
    prompt: "What happens during splash erosion?",
    choices: [
      "Raindrop impact breaks up exposed soil aggregates and scatters particles",
      "Wind carries suspended particles over long distances",
      "A channel deeper than 30 cm forms in a field",
      "A stream removes material from its bank",
    ],
    correctIndex: 0,
    explanation: "Splash erosion is the initial impact of raindrops on bare soil, dislodging and scattering particles.",
    source: "Soil Management lecture",
  },
  {
    id: "gully-depth",
    type: "objective",
    topic: "Soil erosion",
    prompt: "In the course material, a channel deeper than 30 cm formed by running water is classified as:",
    choices: ["Gully erosion", "Splash erosion", "Inter-rill erosion", "Tillage erosion"],
    correctIndex: 0,
    explanation: "The lecture distinguishes gully erosion as channels deeper than 30 cm.",
    source: "Soil Management lecture",
  },
  {
    id: "contour-cultivation",
    type: "objective",
    topic: "Soil conservation",
    prompt: "How is contour cultivation carried out?",
    choices: [
      "Tilling and planting across, rather than down, the natural slope",
      "Planting only at the bottom of a slope",
      "Leaving bare soil between rows",
      "Tilling in the same direction as the steepest slope",
    ],
    correctIndex: 0,
    explanation: "Contour cultivation follows lines across the slope; the ridges help slow runoff and soil transport.",
    source: "Soil Management lecture",
  },
  {
    id: "fertile-productive",
    type: "objective",
    topic: "Soil fertility",
    prompt: "Which statement best distinguishes soil fertility from soil productivity?",
    choices: [
      "Fertility concerns nutrient supply; productivity also depends on environment and management",
      "Fertility measures rainfall; productivity measures soil colour",
      "They mean exactly the same thing in all conditions",
      "Productivity depends only on the soil's clay content",
    ],
    correctIndex: 0,
    explanation: "Productivity depends on fertility as well as environmental variables and the management system.",
    source: "Soil Management lecture",
  },
  {
    id: "soil-components",
    type: "objective",
    topic: "Soil fundamentals",
    prompt: "Which set names the four main components of a well-formed soil?",
    choices: [
      "Mineral matter, organic matter, water and air",
      "Sand, gravel, sunlight and roots",
      "Clay, fertilizer, humus and bedrock",
      "Nitrogen, phosphorus, potassium and water",
    ],
    correctIndex: 0,
    explanation: "The soil-science slides describe mineral matter, organic matter, water and air as the four main components.",
    source: "Soil Science (LAT 406) lecture",
  },
  {
    id: "macro-nutrient",
    type: "objective",
    topic: "Soil fertility",
    prompt: "Which element is listed as a macronutrient in the course materials?",
    choices: ["Nitrogen", "Iron", "Zinc", "Boron"],
    correctIndex: 0,
    explanation: "Nitrogen is one of the listed macronutrients; iron, zinc and boron are listed among micronutrients.",
    source: "Soil Management lecture",
  },
  {
    id: "organic-manure-benefit",
    type: "objective",
    topic: "Soil fertility",
    prompt: "Which is an advantage of organic manure noted in the lecture?",
    choices: [
      "It can improve soil aeration and water transmission",
      "It always supplies nutrients at a faster rate than mineral fertilizer",
      "It eliminates all transport and labour costs",
      "It guarantees that no weeds enter a field",
    ],
    correctIndex: 0,
    explanation: "Organic manures can improve physical soil condition, including aeration and water transmission.",
    source: "Soil Management lecture",
  },
  {
    id: "windbreak-effect",
    type: "objective",
    topic: "Soil conservation",
    prompt: "Which practice is named as a way to reduce wind erosion?",
    choices: ["Installing windbreaks", "Removing crop residues", "Increasing bare-soil exposure", "Tilling repeatedly along the wind"],
    correctIndex: 0,
    explanation: "The lecture lists windbreaks alongside surface cover, crop residues and strip cropping as wind-erosion controls.",
    source: "Soil Management lecture",
  },
  {
    id: "fill-ph-neutral",
    type: "fill",
    topic: "Soil chemistry",
    prompt: "On the pH scale described in the lecture, a value of 7.0 is ____.",
    acceptedAnswers: ["neutral"],
    explanation: "A pH of 7.0 is neutral.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "fill-ph-scale",
    type: "fill",
    topic: "Soil chemistry",
    prompt: "The soil pH scale described in the lecture runs from 0 to ____.",
    acceptedAnswers: ["14", "14.0"],
    explanation: "The material gives a scale from 0.0 to 14.0.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "fill-kaolinite",
    type: "fill",
    topic: "Clay minerals",
    prompt: "The common 1:1 clay mineral example in the lecture is ____.",
    acceptedAnswers: ["kaolinite"],
    explanation: "Kaolinite is presented as the most prominent example of a 1:1 mineral.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "fill-expanding-clay",
    type: "fill",
    topic: "Clay minerals",
    prompt: "Name one expanding 2:1 clay mineral: ____.",
    acceptedAnswers: ["smectite", "vermiculite"],
    explanation: "Smectite and vermiculite are identified as expanding 2:1 minerals.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "fill-ced-holds",
    type: "fill",
    topic: "Soil chemistry",
    prompt: "The negatively charged sites on clay and organic matter hold positively charged ions called ____.",
    acceptedAnswers: ["cations", "exchangeable cations"],
    explanation: "Cations are positively charged ions held at negatively charged sites.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "fill-soil-particle",
    type: "fill",
    topic: "Soil fundamentals",
    prompt: "Soil texture describes the relative proportions of sand, silt and ____.",
    acceptedAnswers: ["clay"],
    explanation: "Texture is based on the relative amounts of the three soil separates: sand, silt and clay.",
    source: "Soil Science (LAT 406) lecture",
  },
  {
    id: "fill-earthworm-breathing",
    type: "fill",
    topic: "Soil biology",
    prompt: "Earthworms exchange gases through their moist body surface by ____.",
    acceptedAnswers: ["diffusion"],
    explanation: "Earthworms have no lungs; gas exchange occurs through the body surface by diffusion.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "fill-earthworm-cast",
    type: "fill",
    topic: "Soil biology",
    prompt: "Earthworm casts can contain more bacteria, organic matter and available plant ____.",
    acceptedAnswers: ["nutrients"],
    explanation: "The lecture notes that casts are enriched in bacteria, organic matter and available nutrients.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "fill-rhizobium",
    type: "fill",
    topic: "Soil biology",
    prompt: "The symbiotic nodule bacterium named in the lecture that fixes nitrogen with legumes is ____.",
    acceptedAnswers: ["rhizobium"],
    explanation: "Rhizobium forms a symbiotic association with legume roots and fixes nitrogen.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "fill-erosion-process",
    type: "fill",
    topic: "Soil erosion",
    prompt: "The three main water-erosion processes are detachment, transport and ____.",
    acceptedAnswers: ["deposition"],
    explanation: "The sequence ends with deposition, which occurs when runoff slows.",
    source: "Soil Management lecture",
  },
  {
    id: "fill-gully",
    type: "fill",
    topic: "Soil erosion",
    prompt: "The lecture classifies water-cut channels deeper than ____ cm as gullies.",
    acceptedAnswers: ["30"],
    explanation: "A gully is described as a channel deeper than 30 cm.",
    source: "Soil Management lecture",
  },
  {
    id: "fill-soil-phases",
    type: "fill",
    topic: "Soil fundamentals",
    prompt: "In the lecture's ideal soil volume composition, soil water occupies ____%.",
    acceptedAnswers: ["25", "25%"],
    explanation: "The slides give 25% water, alongside 45% mineral matter, 5% organic matter and 25% air.",
    source: "Soil Science (LAT 406) lecture",
  },
  {
    id: "fill-contour",
    type: "fill",
    topic: "Soil conservation",
    prompt: "Contour cultivation follows lines at right angles to the natural ____ of the land.",
    acceptedAnswers: ["slope"],
    explanation: "Contour cultivation is carried out across the natural slope.",
    source: "Soil Management lecture",
  },
  {
    id: "subjective-cec",
    type: "subjective",
    topic: "Soil chemistry",
    prompt: "In a sentence or two, explain why CEC matters for plant nutrition.",
    requiredTerms: ["cations", "nutrients"],
    minTerms: 2,
    sampleAnswer: "Negatively charged clay and organic-matter surfaces hold cations, helping retain nutrients for plant uptake.",
    explanation: "A good answer links the soil's negatively charged exchange sites with retaining nutrient cations for plant uptake.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "subjective-soil-ph",
    type: "subjective",
    topic: "Soil chemistry",
    prompt: "Give one reason soil pH matters to plants or soil organisms.",
    requiredTerms: ["nutrient", "availability", "organisms", "roots", "toxic"],
    minTerms: 2,
    sampleAnswer: "Soil pH affects nutrient availability and can limit root or microorganism function when it is too acidic or alkaline.",
    explanation: "The lecture connects pH with nutrient availability, soil organisms, plant roots and possible toxicity at extremes.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "subjective-clay-layers",
    type: "subjective",
    topic: "Clay minerals",
    prompt: "How do 1:1 and expanding 2:1 clay minerals differ when wetted?",
    requiredTerms: ["kaolinite", "water", "interlayer", "expand", "swelling"],
    minTerms: 2,
    sampleAnswer: "Kaolinite is a fixed 1:1 mineral that does not expand, while water enters the interlayer space of expanding 2:1 minerals and pushes their layers apart.",
    explanation: "A complete comparison identifies the fixed 1:1 structure and the water-driven expansion of some 2:1 minerals.",
    source: "Soil Chemical Properties lecture",
  },
  {
    id: "subjective-soil-biota",
    type: "subjective",
    topic: "Soil biology",
    prompt: "Name two ways soil organisms contribute to soil quality or fertility.",
    requiredTerms: ["nutrient", "decomposition", "structure", "humus", "weathering"],
    minTerms: 2,
    sampleAnswer: "Soil organisms decompose organic residues and recycle nutrients; they also help form humus and stabilise soil structure.",
    explanation: "The course materials include nutrient cycling, decomposition, humus formation, soil development and structural stabilisation.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "subjective-earthworms",
    type: "subjective",
    topic: "Soil biology",
    prompt: "Describe two beneficial effects earthworms can have on soil.",
    requiredTerms: ["burrow", "aeration", "drainage", "casts", "nutrients", "aggregates"],
    minTerms: 2,
    sampleAnswer: "Their burrows improve aeration and drainage, while casts can enrich soil with organic matter and available nutrients.",
    explanation: "Earthworms can improve aeration, drainage, mixing and aggregation; their casts may contain available nutrients.",
    source: "Soil Biological Properties lecture",
  },
  {
    id: "subjective-erosion-types",
    type: "subjective",
    topic: "Soil erosion",
    prompt: "Distinguish rill erosion from gully erosion.",
    requiredTerms: ["shallow", "channel", "30 cm", "deeper"],
    minTerms: 2,
    sampleAnswer: "Rill erosion removes soil through shallow channels, whereas gully erosion creates channels deeper than 30 cm.",
    explanation: "The lecture describes rills as shallow channels and gullies as water-cut channels deeper than 30 cm.",
    source: "Soil Management lecture",
  },
  {
    id: "subjective-erosion-controls",
    type: "subjective",
    topic: "Soil conservation",
    prompt: "Describe two soil-conservation practices and how they reduce water erosion.",
    requiredTerms: ["cover", "runoff", "slope", "residue", "contour", "infiltration", "terrace"],
    minTerms: 2,
    sampleAnswer: "Cover crops protect the surface and improve infiltration, while contour cultivation slows runoff by working across the slope.",
    explanation: "Good answers pair named practices such as cover cropping, residue retention, contouring or terracing with reduced detachment or runoff.",
    source: "Soil Management lecture",
  },
  {
    id: "subjective-fertility",
    type: "subjective",
    topic: "Soil fertility",
    prompt: "Why might a fertile soil not always be a productive soil?",
    requiredTerms: ["nutrient", "environment", "management", "fertility"],
    minTerms: 2,
    sampleAnswer: "Fertility describes nutrient supply, but productivity also depends on environmental conditions and the way the soil is managed.",
    explanation: "The lecture defines productivity as a function of fertility, environmental variables and the management system.",
    source: "Soil Management lecture",
  },
  {
    id: "subjective-organic-manure",
    type: "subjective",
    topic: "Soil fertility",
    prompt: "Give one advantage and one limitation of organic manure.",
    requiredTerms: ["aeration", "water", "nutrients", "slow", "labour", "transport", "heavy metals"],
    minTerms: 2,
    sampleAnswer: "Organic manure can improve aeration and water transmission, but it may be bulky to transport and its nutrients can mineralise slowly.",
    explanation: "The slides list improvements to soil physical condition as benefits, and slow mineralisation and handling costs among limitations.",
    source: "Soil Management lecture",
  },
  {
    id: "subjective-degradation",
    type: "subjective",
    topic: "Soil management",
    prompt: "What is soil degradation, and what can it mean for production?",
    requiredTerms: ["quality", "physical", "chemical", "biological", "productivity"],
    minTerms: 2,
    sampleAnswer: "Soil degradation is a decline in soil quality involving physical, chemical or biological changes, and it can reduce current or future productivity.",
    explanation: "The course defines degradation as deterioration in soil properties and processes, with a consequent decline in productivity.",
    source: "Soil Management lecture",
  },
  {
    id: "subjective-ideal-soil",
    type: "subjective",
    topic: "Soil fundamentals",
    prompt: "Name two properties of an ideal soil for crop growth from the course materials.",
    requiredTerms: ["organic matter", "crumb", "texture", "nutrients", "aeration", "water holding", "infiltration", "pH", "rooting depth"],
    minTerms: 2,
    sampleAnswer: "An ideal soil has organic matter, a crumb structure, good aeration and water-holding capacity, suitable pH and effective rooting depth.",
    explanation: "The lecture's ideal-soil list includes organic matter, crumb structure, texture, nutrients, aeration, water relations, pH and rooting depth.",
    source: "Soil Management lecture",
  },
  {
    id: "walkley-black-oxidation",
    type: "objective",
    topic: "Soil carbon practical",
    prompt: "What does the Walkley–Black wet-combustion method estimate in soil?",
    choices: [
      "Easily oxidizable organic carbon",
      "Total nitrogen in plant tissue",
      "The percentage of clay in a soil",
      "Available phosphorus in irrigation water",
    ],
    correctIndex: 0,
    explanation: "The practical exam identifies Walkley–Black wet combustion as a method for determining easily oxidizable soil carbon.",
    source: "LAT 313B Soil Science Practical exam; GLOSOLAN soil-carbon SOP",
  },
  {
    id: "walkley-black-carbon-fraction",
    type: "objective",
    topic: "Soil carbon practical",
    prompt: "According to the LAT 313B practical exam, approximately what fraction of soil carbon is determined by the Walkley–Black wet-combustion method?",
    choices: ["77%", "25%", "50%", "100%"],
    correctIndex: 0,
    explanation: "The exam material states that wet combustion in the Walkley–Black method determines about 77% of easily oxidizable carbon.",
    source: "LAT 313B Soil Science Practical exam",
  },
  {
    id: "walkley-black-titrant",
    type: "objective",
    topic: "Soil carbon practical",
    prompt: "Which solution is used to titrate the excess dichromate in the Walkley–Black titration method?",
    choices: [
      "Ferrous sulfate solution",
      "Sodium hydroxide solution",
      "Ammonium molybdate solution",
      "Bray-1 extracting solution",
    ],
    correctIndex: 0,
    explanation: "The SOP specifies ferrous sulfate or ferrous ammonium sulfate as the titrant for excess dichromate.",
    source: "GLOSOLAN soil-carbon SOP",
  },
  {
    id: "ph-575-interpretation",
    type: "objective",
    topic: "Soil chemistry",
    prompt: "A soil sample has a pH of 5.75. How is this value interpreted in the LAT 313B practical exam?",
    choices: ["Moderately acidic", "Neutral", "Strongly alkaline", "Exactly pH-neutral"],
    correctIndex: 0,
    explanation: "The practical exam's worked interpretation describes pH 5.75 as moderately acidic.",
    source: "LAT 313B Soil Science Practical exam",
  },
  {
    id: "soil-sample-preparation",
    type: "objective",
    topic: "Soil laboratory practice",
    prompt: "Which sequence contains only soil-sample preparation steps listed in the practical exam?",
    choices: [
      "Mixing and quartering, air-drying, grinding and sieving",
      "Heating, dissolving, fermenting and cooling",
      "Titrating, filtering, igniting and washing",
      "Compressing, freezing, dissolving and staining",
    ],
    correctIndex: 0,
    explanation: "The exam lists mixing and quartering, air-drying, grinding and sieving as steps used to prepare a soil sample for analysis.",
    source: "LAT 313B Soil Science Practical exam",
  },
  {
    id: "fill-walkley-equivalence",
    type: "fill",
    topic: "Soil carbon practical",
    prompt: "In the GLOSOLAN SOP, 1 mL of 1 N dichromate solution is equivalent to ____ mg of carbon.",
    acceptedAnswers: ["3", "3 mg"],
    explanation: "The SOP states that 1 mL of 1 N dichromate solution is equivalent to 3 mg of carbon.",
    source: "GLOSOLAN soil-carbon SOP",
  },
  {
    id: "fill-carbon-calculation",
    type: "fill",
    topic: "Soil carbon practical",
    prompt: "A 0.5 g soil sample contains 2.25% carbon. How many grams of carbon does the sample contain?",
    acceptedAnswers: ["0.01125", "0.01125 g"],
    explanation: "Multiply the sample mass by the carbon fraction: 0.5 g × 0.0225 = 0.01125 g.",
    source: "LAT 313B Soil Science Practical exam",
  },
  {
    id: "fill-walkley-reaction-time",
    type: "fill",
    topic: "Soil carbon practical",
    prompt: "In the GLOSOLAN titration procedure, the insulated flask stands for ____ minutes after the reaction mixture is prepared.",
    acceptedAnswers: ["30", "30 minutes"],
    explanation: "The SOP specifies a 30-minute standing period in a fume hood.",
    source: "GLOSOLAN soil-carbon SOP",
  },
  {
    id: "fill-soil-carbon-reporting",
    type: "fill",
    topic: "Soil carbon practical",
    prompt: "The GLOSOLAN SOP says to report organic carbon on an oven-dry basis to ____ decimal places.",
    acceptedAnswers: ["two", "2", "two decimal places", "2 decimal places"],
    explanation: "The SOP specifies reporting oven-dry-basis organic carbon to two decimal places.",
    source: "GLOSOLAN soil-carbon SOP",
  },
  {
    id: "subjective-walkley-principle",
    type: "subjective",
    topic: "Soil carbon practical",
    prompt: "Briefly describe the principle behind the Walkley–Black method for soil organic carbon.",
    requiredTerms: ["organic carbon", "dichromate", "oxidation", "sulfuric acid"],
    minTerms: 2,
    sampleAnswer: "The method oxidizes soil organic carbon with dichromate in a strongly acidic sulfuric-acid medium, then determines the remaining dichromate by titration or colorimetry.",
    explanation: "A good response identifies oxidation of soil organic carbon by dichromate in an acidic medium.",
    source: "GLOSOLAN soil-carbon SOP",
  },
  {
    id: "subjective-sample-preparation",
    type: "subjective",
    topic: "Soil laboratory practice",
    prompt: "Name two steps used to prepare a soil sample for laboratory analysis.",
    requiredTerms: ["mixing and quartering", "air drying", "grinding", "sieving"],
    minTerms: 2,
    sampleAnswer: "The sample requires mixing and quartering, air drying, grinding and sieving before analysis.",
    explanation: "The practical exam lists mixing and quartering, air-drying, grinding and sieving as sample-preparation steps.",
    source: "LAT 313B Soil Science Practical exam",
  },
  {
    id: "phosphorus-colorimetry",
    type: "objective",
    topic: "Soil laboratory practice",
    prompt: "In the practical exam's phosphorus colorimetry method, what is used to reduce the phosphate–ammonium molybdate complex?",
    choices: ["Ascorbic acid", "Sodium hydroxide", "Ferrous sulfate", "Potassium dichromate"],
    correctIndex: 0,
    explanation: "The exam states that ascorbic acid reduces the complex formed between phosphate and ammonium molybdate.",
    source: "LAT 313B Soil Science Practical exam",
  },
  {
    id: "fill-phosphorus-calculation",
    type: "fill",
    topic: "Soil laboratory practice",
    prompt: "A 1 g soil sample is extracted with 10 mL Bray-1 solution. Five millilitres of extract are diluted to 25 mL, then 5 mL of that solution are diluted again to 25 mL. The calibration curve is A = 0.65x and absorbance is 0.250. Calculate available phosphorus in mg/kg (2 decimal places).",
    acceptedAnswers: ["96.15", "96.15 mg/kg"],
    explanation: "The measured solution contains 0.250 ÷ 0.65 = 0.3846 µg/mL. Two five-fold dilutions give a dilution factor of 25. Multiplying by 25 × 10 mL and dividing by 1 g gives 96.15 µg/g, equivalent to 96.15 mg/kg.",
    source: "LAT 313 A&B.pdf · page 2, question 12",
  },
  {
    id: "fill-nitrogen-mass",
    type: "fill",
    topic: "Soil laboratory practice",
    prompt: "A 0.55 g soil sample contains 0.13% nitrogen. How many grams of nitrogen are in the sample?",
    acceptedAnswers: ["0.000715", "0.000715 g", "7.15 × 10^-4 g", "7.15e-4 g"],
    explanation: "Convert 0.13% to 0.0013 and multiply by 0.55 g: 0.000715 g nitrogen.",
    source: "LAT 313B Soil Science Practical exam",
  },
];
